In [1]:
import pandas as pd

In [5]:
a = [1, 7, 2]
var = pd.Series(a)
print(var)
print(type(var))
print(var[2])

0    1
1    7
2    2
dtype: int64
<class 'pandas.core.series.Series'>
2


In [6]:
var1 = pd.Series(a, index = ["x", "y", "z"])
print(var1)
print(var1["y"])

x    1
y    7
z    2
dtype: int64
7


In [7]:
y = {"x": 1, "y": 7, "z": 2}

var2 = pd.Series(y)
print(var2)

x    1
y    7
z    2
dtype: int64


In [9]:
var3 = {
    "cal": [100,200,300],
    "dura": [2, 4, 6]
}

df = pd.DataFrame(var3)
print(df)

   cal  dura
0  100     2
1  200     4
2  300     6


In [16]:
print(df.loc[[0, 1]])
print(type(df.loc[[0, 1]]))

   cal  dura
0  100     2
1  200     4
<class 'pandas.core.frame.DataFrame'>


In [17]:
df = pd.read_csv('practice.csv')
print(df)

   index  class  marks
0      1      5     80
1      2      6     90
2      3      7     20
3      4      8    100
4      5      9     20


In [18]:
import torch

In [19]:
torch.__version__

'2.8.0+cu126'

In [29]:
a = torch.tensor(7)

print(a)
print(a.item())
print(a.dtype)
print(a.shape)
print(a.size())

tensor(7)
7
torch.int64
torch.Size([])
torch.Size([])


In [30]:
dime = a.ndim
print(dime)

0


In [44]:
a = torch.tensor([1.0, 2.0, 3.0])

# print(a)
# # print(a.item())
# print(a.dtype)
# print(a.shape)
# print(a.size())
# print(a.ndim)
# print(a[0].item())
print(torch.sum(a).item())
print(torch.mean(a).item())
print(torch.norm(a).item())
print(type(torch.norm(a)))

6.0
2.0
3.7416574954986572
<class 'torch.Tensor'>


In [49]:
a = torch.tensor([[[7,8,9], [0,1,2]], [[1,2,3], [4,5,6]]])

print(a)
# print(a.item())
print(a.dtype)
print(a.shape)
print(a.size())
print(a.ndim)
# print(a[0].item())

tensor([[[7, 8, 9],
         [0, 1, 2]],

        [[1, 2, 3],
         [4, 5, 6]]])
torch.int64
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
3


In [56]:
zero = torch.zeros(3, 4)
print(zero)
print(zero.shape)
print(zero.dtype)
print(zero.device)
print(zero.numel()) # it returns the total number of elements present in the current tensor object.

print(zero.element_size() * zero.numel()) # in bytes.

print(torch.sum(zero).item())
print(torch.std(zero).item())

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])
torch.float32
cpu
12
48
0.0
0.0


In [59]:
one = torch.ones(size=(3,4), dtype=torch.int64)
print(one)
print(one.shape)
print(one.dtype)
print(one.device)
print(one.numel()) # it returns the total number of elements present in the current tensor object.

print(one.element_size() * one.numel()) # in bytes.

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
torch.Size([3, 4])
torch.int64
cpu
12
96


In [67]:
random = torch.rand(3,4)

print(random)

tensor([[0.2725, 0.8468, 0.7708, 0.3425],
        [0.2986, 0.2581, 0.8096, 0.4471],
        [0.4310, 0.3731, 0.9017, 0.5347]])


In [84]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random = torch.rand(3,4)

print(random)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [87]:
var = torch.tensor([1,2,3])
var * 10

tensor([10, 20, 30])

In [90]:
print(var * var)

## * in tensors means that we are doing an element-wise multiplication.

# [1, 2, 3] * [1, 2, 3]
# [1*1, 2*2, 3*3]
# [1, 4, 9]

tensor([1, 4, 9])


In [91]:
print(var)
print(var.shape)

matrix_res = torch.matmul(var, var)
print(matrix_res)
print(matrix_res.shape)

tensor([1, 2, 3])
torch.Size([3])
tensor(14)
torch.Size([])


In [92]:
var @ var

tensor(14)

In [2]:
import torch

cude_avail = torch.cuda.is_available()

if cude_avail:
  print(torch.cuda.get_device_name(0))
  print(dir(torch.cuda))
  print(torch.cuda.current_device())
  print(torch.cuda.get_device_properties(0))
else:
  print("GPU not available.")

GPU not available.


In [ ]:
# 3 errors that are common, please don't make them -

# 1. the matrix sizes should be compatible with each other, otherwise you get a runtime error.
# 2. the data types of the tensors should be same, if you want to perform any operations between them.
# 3. if you are performing operations on two tensors which are present on two different devices like CPU and cuda, then again you will get a runtime error.